config/routes.rb
Rails.application.routes.draw do
    devise_scope :user do
        authenticated :user do 
            root to: 'home#dashboard', as: :authenticated_root
        end

        unauthenticated do
            root to: 'devise/sessions#new', as: :unauthenticated_root
        end
    end

    root to: 'home#index'
  devise_for :users

  resources :microposts, except: :new, constraints: {id: /[0-9]+/}
  post '/microposts/:id/add_to_current_report', to: 'microposts#add_to_current_report', as: 'add_mp_to_current_report'
  post '/microposts/:id/remove_from_current_report', to: 'microposts#remove_from_current_report', as: 'remove_mp_from_current_report'
  resources :publications
  get '/publications/:id/pdf', to: 'publications#pdf', as: 'publication_pdf'
  get '/microposts/:id/tex', to: 'microposts#tex', as: 'micropost_tex'
  get '/publications/:id/info', to: 'publications#info', as: 'publication_info'
  post '/misc/getPublicationIds', to: 'publications#getIds'
  resources :projects do
  end
  post '/projects/:id/leave', to: 'projects#leave', as: "leave_project"
  get '/projects/:id/microposts', to: 'projects#microposts', as: "project_microposts"
  get '/projects/:id/publications', to: 'projects#publications', as: "project_publications"
  get '/projects/:id/sharesettings', to: 'projects#sharesettings', as: "project_sharesettings"
  post '/projects/:id/share_with_user', to: 'projects#share_with_user', as: "project_share_with_user"
  post '/projects/:id/set_user_permission', to: 'projects#set_user_permission', as: "project_set_user_permission"
  post '/projects/:id/kick_user', to: 'projects#kick_user', as: "project_kick_user"
  post '/projects/:id/set_as_current', to: 'projects#set_as_current', as: "project_set_as_current"
  get '/projects/:project_id/publication/:id', to: 'publications#show', as: "project_publication"
  resources :reports do 
  end
  post '/reports/:id/leave', to: 'reports#leave', as: "leave_report"
  get '/reports/:id/microposts', to: 'reports#microposts', as: "report_microposts"
  get '/reports/:id/publications', to: 'reports#publications', as: "report_publications"
  get '/reports/:id/sharesettings', to: 'reports#sharesettings', as: "report_sharesettings"
  post '/reports/:id/share_with_user', to: 'reports#share_with_user', as: "report_share_with_user"
  post '/reports/:id/set_user_permission', to: 'reports#set_user_permission', as: "report_set_user_permission"
  post '/reports/:id/kick_user', to: 'reports#kick_user', as: "report_kick_user"
  post '/reports/:id/set_as_current', to: 'reports#set_as_current', as: "report_set_as_current"
  get '/reports/:report_id/publication/:id', to: 'publications#show', as: "report_publication"

  get '/users/:username/stats', to: 'user#stats', as: "user_stats"
  get '/users/:username', to: 'user#show', as: "user"
  get '/users/:username/microposts', to: 'user#microposts', as: "user_microposts"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mathjax 'mathjax'

  get '/settings', to: 'user#settings'
  put '/settings/update_password', to: 'user#update_password'

end

app/models/publication.rb
class Publication < ApplicationRecord
    has_attached_file :pdf
    validates_attachment_content_type :pdf, content_type: %r"application/pdf.*"
    belongs_to :user
    belongs_to :project

    validates_presence_of :user
    validates_presence_of :project
    validates_presence_of :bibtex
    validates_presence_of :author
    validates_presence_of :title
    validates_presence_of :ref
    validates_uniqueness_of :ref, scope: :project_id




    def parseBibTeX!
        bt = BibTeX.parse self.bibtex
        b = bt.first
        self.author = b.author
        self.title = b.title
        self.ref = b.key

        if bt.errors.empty?
            return true
        else 
            self.errors.add(:base, bt.errors)
            return false
        end
    end

    def copy_to_project project
      pub = self.dup
      pub.project_id = project.id
      pub.save
      return pub
    end

    def self.filter(query, current_user)
      f = PublicationsFilter.new
      f.current_user = current_user
      f.query = query
      return f.publications
    end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
    before_action :set_publication, only: [:show, :edit, :update, :destroy, :pdf]
    before_action :authenticate_user!

    # GET /publications
    # GET /publications.json
    def index
      @query = params[:filter]
      if params[:filter]
        @publications = Publication.filter params[:filter], current_user
      else
        @publications = Publication.filter "", current_user
      end
    end

    # GET /publications/1
    # GET /publications/1.json
    def show
        if @publication.nil?
            render :missing
        else
            render :show
        end
    end


    # GET /publications/new
    def new
        @publication = Publication.new
    end

    # GET /publications/1/edit
    def edit
      (render_404 and return) unless current_user.can_write @publication.project
      
    end

    # POST /publications
    # POST /publications.json
    def create
        @publication = Publication.new(publication_params)
        @publication.user = current_user

        parsed = false
        if @publication.parseBibTeX!
            parsed = true
        end

        respond_to do |format|
            if parsed and @publication.save 
                format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
                format.json { render :show, status: :created, location: @publication }
            else
                format.html { render :new }
                format.json { render json: @publication.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /publications/1
    # PATCH/PUT /publications/1.json
    def update
        respond_to do |format|
            parsed = false
            if @publication.parseBibTeX!
                parsed = true
            end
            if parsed and @publication.update(publication_params)
                format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
                format.json { render :show, status: :ok, location: @publication }
            else
                format.html { render :edit }
                format.json { render json: @publication.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /publications/1
    # DELETE /publications/1.json
    def destroy
        @publication.destroy
        respond_to do |format|
            format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def pdf
        @title = @publication.ref
        send_data File.open(@publication.pdf.path).read, disposition: 'inline', filename: "#{@publication.ref}.pdf", type: "application/pdf"
    end

    def getIds
        ps = params.require(:refs)
        ids = ps.map do |project, ref| 
            p = project.publications.find_by ref: ref
            if p.nil?
                -1
            else
                p.id
            end
        end


        render json: ids
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
        if params[:project_id]
            @p = Project.find_by id: params[:project_id] 
            return unless current_user.can_read(@p)
            return if @p.nil?
            if (/^[0-9]+$/ =~ params[:id]).nil? 
              @publication = @p.publications.find_by ref: params[:id]
            else
              @publication = @p.publications.find_by id: params[:id] 
            end
        else 
          @publication = Publication.find_by id: params[:id]
          return if @publication.nil?
          @publication = nil if !(current_user.can_read @publication.project)
        end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.fetch(:publication, {}).permit([:bibtex, :pdf, :project_id])
    end

end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.haml
- path = @publication.new_record? ? publications_path : publication_path(@publication)
= form_for @publication, url: path, html: { multipart: true } do |f|
  end
  - if @publication.errors.any?
    #error_explanation
      %h2= "#{pluralize(@publication.errors.count, "error")} prohibited this publication from being saved:"
      %ul
        - @publication.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :project
    = f.collection_select(:project_id, current_user.all_projects, :id, :name)
  .form-group
    = f.label :bibtex
    = f.text_area :bibtex, class: "form-control", rows: 20
  .form-group
    = f.label :pdf
    = f.file_field :pdf, class: "form-control"

  .actions
    = f.submit 'Save'

app/views/publications/_publication_block.haml
.publication.publication_block
  %a.col-sm-8{href: publication_path(publication)}
    %h4= publication.author
    %h5= publication.title
    %code.ref{id: publication.ref}=publication.ref
  .col-sm-4
    %span.input-group-btn
      %button{class: "btn btn-default clipboard-btn align-right", data: {clipboard_action: "copy", clipboard_target: "##{ publication.ref }"}} Copy ref
    

app/views/publications/edit.html.haml
%h1 Editing publication

= render 'form'

= link_to 'Show', @publication
\|
= link_to 'Back', publications_path

app/views/publications/index.html.haml
.hidden.publications#index
.panel
  =form_tag publications_path, class: "form form-horizontal", method: :get do
    =label_tag :filter, nil, class: "col-sm-1 control-label"
    .col-sm-8
      =text_field_tag :filter, nil, class: "form-control", value: @query
    =submit_tag 'Apply', class: "btn btn-default col-sm-2"

  - if @publications.empty?
    %p No publications found
  - else 
    .infinite-table
      - @publications.each do |publication|
        = render partial: 'publication_block', object: publication, as: 'publication'





  = link_to 'New Publication', new_publication_path

app/views/publications/missing.html.haml
.panel
  %h4 
    Publication 
    %code= params[:id]
    not found

  - if @idbyref
    %h5 Was trying to find it by reference

  =link_to 'Add it to database', new_publication_path

app/views/publications/new.html.haml
%h1 New publication

= render 'form'

= link_to 'Back', publications_path

app/views/publications/show.html.haml
.hidden.publications#edit
%p#notice= notice
.panel.panel-default
  .panel-heading
    %h3.panel-title= @publication.author
    %h5= @publication.title
    %h6
      Project:
      =link_to @publication.project.name, project_path(@publication.project)
  .panel-body
    .form-group
      %label \cite{}
      .input-group
        %input.form-control#ref{type: :text, value: @publication.ref}/
        %span.input-group-btn
          =fa_icon "copy", class: "btn btn-default clipboard-btn", data: {clipboard_action: "copy", clipboard_target: "#ref"}
    .form-group
      %label BibTeX
      %pre#bibtex= @publication.bibtex
      %span.input-group-btn
        %button{class: "btn btn-default clipboard-btn", data: {clipboard_action: "copy", clipboard_target: "#bibtex"}} Copy BibTeX to clipboard
    - if @publication.pdf.present?
      .form-group
        %label PDF 
        %iframe{src: @publication.pdf.url, class: "pdf form-control"}
      =button_to 'Download PDF', publication_pdf_path(@publication), target: "_blank", type: "button", class: "btn btn-default", method: :get
    - if current_user.can_write @publication.project
      = link_to 'Edit', edit_publication_path(@publication)