config/routes.rb
Rails.application.routes.draw do
    devise_scope :user do
        authenticated :user do 
            root to: 'home#dashboard', as: :authenticated_root
        end

        unauthenticated do
            root to: 'devise/sessions#new', as: :unauthenticated_root
        end
    end

    root to: 'home#index'
  devise_for :users

  resources :microposts, except: :new, constraints: {id: /[0-9]+/}
  post '/microposts/:id/add_to_current_report', to: 'microposts#add_to_current_report', as: 'add_mp_to_current_report'
  post '/microposts/:id/remove_from_current_report', to: 'microposts#remove_from_current_report', as: 'remove_mp_from_current_report'
  resources :publications
  get '/publications/:id/pdf', to: 'publications#pdf', as: 'publication_pdf'
  get '/microposts/:id/tex', to: 'microposts#tex', as: 'micropost_tex'
  get '/publications/:id/info', to: 'publications#info', as: 'publication_info'
  post '/misc/getPublicationIds', to: 'publications#getIds'
  resources :projects do
  end
  post '/projects/:id/leave', to: 'projects#leave', as: "leave_project"
  get '/projects/:id/microposts', to: 'projects#microposts', as: "project_microposts"
  get '/projects/:id/publications', to: 'projects#publications', as: "project_publications"
  get '/projects/:id/sharesettings', to: 'projects#sharesettings', as: "project_sharesettings"
  post '/projects/:id/share_with_user', to: 'projects#share_with_user', as: "project_share_with_user"
  post '/projects/:id/set_user_permission', to: 'projects#set_user_permission', as: "project_set_user_permission"
  post '/projects/:id/kick_user', to: 'projects#kick_user', as: "project_kick_user"
  post '/projects/:id/set_as_current', to: 'projects#set_as_current', as: "project_set_as_current"
  get '/projects/:project_id/publication/:id', to: 'publications#show', as: "project_publication"
  resources :reports do 
  end
  post '/reports/:id/leave', to: 'reports#leave', as: "leave_report"
  get '/reports/:id/microposts', to: 'reports#microposts', as: "report_microposts"
  get '/reports/:id/publications', to: 'reports#publications', as: "report_publications"
  get '/reports/:id/sharesettings', to: 'reports#sharesettings', as: "report_sharesettings"
  post '/reports/:id/share_with_user', to: 'reports#share_with_user', as: "report_share_with_user"
  post '/reports/:id/set_user_permission', to: 'reports#set_user_permission', as: "report_set_user_permission"
  post '/reports/:id/kick_user', to: 'reports#kick_user', as: "report_kick_user"
  post '/reports/:id/set_as_current', to: 'reports#set_as_current', as: "report_set_as_current"
  get '/reports/:report_id/publication/:id', to: 'publications#show', as: "report_publication"

  get '/users/:username/stats', to: 'user#stats', as: "user_stats"
  get '/users/:username', to: 'user#show', as: "user"
  get '/users/:username/microposts', to: 'user#microposts', as: "user_microposts"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mathjax 'mathjax'

  get '/settings', to: 'user#settings'
  put '/settings/update_password', to: 'user#update_password'

end

app/models/project.rb
class Project < ApplicationRecord 
    belongs_to :owner, class_name: "User"

    has_many :user_projects
    has_many :publications

    has_many :users, through: :user_projects, source: :user

    has_many :user_projects_readable, -> {where level: 'r'}, class_name: "UserProject"
    has_many :readers, class_name: "User", through: :user_projects_readable, source: :user

    has_many :user_projects_writeable, -> {where level: 'w'}, class_name: "UserProject"
    has_many :writers,  class_name: "User", through: :user_projects_writeable, source: :user

    has_many :user_projects_manageable, -> {where level: 'm'}, class_name: "UserProject"
    has_many :managers,  class_name: "User", through: :user_projects_manageable, source: :user

    has_many :microposts
    before_save :create_share_link
    before_destroy :destroy_shares

    validates_presence_of :owner
    validates_presence_of :name
    validates_uniqueness_of :share_link

    def add_reader(user)
        begin 
            self.users.delete user
            self.readers << user
        end  unless user == owner
    end

    def add_readers(users)
        begin 
            self.users.delete users
            self.readers << users.select{|user| user != owner}
        end 
    end

    def add_writer(user)
        begin 
            self.users.delete user
            self.writers << user 
        end unless user == owner
    end
    def add_writers(users)
        begin 
            self.users.delete users
            self.writers << users.select{|user| user != owner}
        end
    end

    def add_manager(user)
        begin 
            self.users.delete user
            self.managers << user 
        end unless user == owner
    end
    def add_managers(users)
        begin 
            self.users.delete users
            self.managers << users.select{|user| user != owner}
        end
    end

    def kick user
        self.users.delete user
    end

    def pass_ownership_to user
        prev_owner = self.owner
        self.owner = user
        save
        add_manager prev_owner
    end

    def change_permission user, permission
        u_p = user_projects.find_by(user_id: user.id)
        if u_p 
            u_p.set_permission permission
            u_p.save
        else
            case permission
            when :write
                add_writer user
            when :read 
                add_reader user
            when :manage
                add_manager user
            end
        end
    end

    def user_permission user
        u_p = user_projects.find_by(user_id: user.id) and u_p.permission
    end

    def create_share_link
        self.share_link = SecureRandom.urlsafe_base64(32)
    end

    def share_by_link
        self.is_shared_with_link = true
    end

    def stop_sharing_by_link
        self.is_shared_with_link = false
    end


    def all_users
        users.to_a << owner
    end


    def users_with_permissions
      self.users.select('*, users.id as id, user_projects.level as level').map
    end

    private
    def destroy_shares
        self.user_projects.delete_all
    end

end

app/controllers/projects_controller.rb
require Rails.root.join('app/models/user_project.rb')
class ProjectsController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_project, except: %i[index new create share_with_user]
  before_action :set_permissions, except: %i[index new create share_with_user]

  # GET /projects
  # GET /projects.json
  def index
    @own_projects = current_user.own_projects
    @projects = current_user.projects_with_permissions
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    (render_404 and return) unless @can_read
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.owner_id = current_user.id
  end

  # GET /projects/1/edit
  def edit;
    (render_404 and return) unless @can_manage
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params.permit(%i[owner_id name description git_url]) )

    respond_to do |format|
      if @project.save
        format.html do
          redirect_to @project,
            notice: 'Project was successfully created.'
        end
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    (render_404 and return) unless @can_manage
    respond_to do |format|
      if @project.update(project_params.permit(%i[name git_url description]) )
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def leave
    unless @can_leave
      redirect_to project_path(@project), flash: { error: "You can't leave your own project. You may delete it or pass ownership to somebody else." }
    end

    current_user.leave_project(@project)
    redirect_to projects_path, notice: "You've left project #{@project.name}"
  end

  def sharesettings
    unless @can_manage
      redirect_to project_path(@project), flash: { error: "You don't have rights to manage this project" }
    end
  end

  def share_with_user
    prms = params.permit([:username, :id, :async])
    @project = Project.find_by(id: prms[:id])
    set_permissions
    (render_404 and return) unless @can_manage

    username = prms[:username]
    @user = User.find_by(username: username)
    errors = []
    status = :success
    user = nil

    if @project.nil?
      errors << "No project found with id #{prms[:id]}"
      status = :fail
    elsif @user.nil?
      errors << "No user found with username #{username}"
      status = :fail
    elsif @user.in? @project.users
      errors << "User #{username} already has permissions in this project"
      status = :fail
    elsif @user == @project.owner
      errors << "User #{username} is owner of this project"
      status = :fail
    else
      if @project.add_reader @user 
        status = :success
        user = @user
      else
        status = :fail
        errors << "Unknown error"
      end
    end

    if prms[:async]
      render json: {status: status, errors: errors, user: user.to_json}
    else 
      redirect_to project_sharesettings_path(@project)
    end
  end
  
  def set_user_permission 
    (render_404 and return) unless @can_manage
    prms = params.permit([:username, :level, :async])

    user = User.find_by(username: prms[:username])
    level = prms[:level]
    async = prms[:async]

    errors = []
    status = :success
    permission = UserProject::ClassMethods.level_to_permission level

    if user.nil?
      status = :fail
      errors << "No user found with id #{prms[:username]}"
    elsif !(user.in? @project.users)
      status = :fail
      errors << "User #{user.username} isn't participating in this project"
    else
      if @project.change_permission user, permission
        status = :success
      else
        status = :fail
        errors << "Unknown error"
      end
    end

    if async
      render json: {status: status, errors: errors, level: level}
    else
      #redirect_to project_sharesettings_path(@project)
      redirect_to project_sharesettings_path(@project)
    end

  end

  def kick_user
    (render_404 and return) unless @can_manage
    prms = params.permit([:username, :async])
    user = User.find_by username: prms[:username]
    errors = []
    status = :success

    if user.nil?
      status = :fail
      errors << "No user found with id #{prms[:username]}"
    elsif user == @project.owner
      status = :fail
      errors << "Can't kick owner"
    elsif !(user.in? @project.users)
      status = :fail
      errors << "User with id #{prms[:username]} isn't participant of this project"
    else
      if @project.kick user
        status = :success
      else
        status = :fail
        errors << "Unknown error"
      end
    end

    if prms[:async]
      render json: {status: status, errors: errors}
    else
      redirect_to project_sharesettings_path(@project)
    end


  end

  def set_as_current
    (render_404 and return) unless @can_write

    current_user.current_project = @project

    render json: {status: "success"}
  end

  def microposts
    redirect_to microposts_path(filter: "project:##{@project.id}")
  end

  def publications
    redirect_to publications_path(filter: "project:##{@project.id}")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find_by(id: params[:id])
    render_404 if @project.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.fetch(:project, {})
  end

  def set_permissions
    @is_owner = @project.owner == current_user
    @can_leave = !@is_owner
    if @is_owner
      @can_manage = true
      @can_write = true
      @can_read = true
    else
      perm = @project.user_permission(current_user)
      unless perm.nil?
        @can_read = perm.in? %i[read write manage]
        @can_write = perm.in? %i[write manage]
        @can_manage = perm.in? [:manage]
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project, html: { class: " form-horizontal" } do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg
  =f.hidden_field :owner_id
  .form-group
    =f.label :name, class: "control-label col-sm-2"
    .col-sm-10
      =f.text_field :name, class: 'form-control'
  .form-group
    =f.label :git_url, class: "control-label col-sm-2"
    .col-sm-10
      =f.text_field :git_url, class: 'form-control'
  .form-group
    =f.label :description, class: "control-label col-sm-2"
    .col-sm-10
      =f.text_area :description, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      -if @action == :edit
        = f.submit 'Save', class: 'btn btn-default'
      -else
        = f.submit 'Create', class: 'btn btn-default'

app/views/projects/edit.html.haml
.panel
  %h2 Editing project

  -@action = :edit
  =render 'form'

app/views/projects/index.html.haml
.hidden.projects#index
.panel 
  .row
    .col-md-8
      %h2 My projects
    .col-md-4
      %a.btn.btn-primary.align-right{href: new_project_path}
        Create project
  - @own_projects.each do |project|
    .well.well-sm
      .project.own-project{id: "id#{project.id}"}
        %a.project-name{href: project_path(project)}= project.name
        - is_current = project == current_user.current_project
        -cl = is_current ? "is-current btn btn-success disabled" : "is-not-current btn btn-default"
        -text = is_current ? "Current" : "Make current"
        -icon = is_current ? "check-square-o" : "square-o"
        =link_to project_set_as_current_path(project), class: "project-is-current-indicator #{cl} align-right" do 
          = fa_icon icon
          = text
          

        .project-privacy-indicator.align-right{class: project.is_shared_with_link ? "project-shared-with-link" : ""}
        %a.project-edit-link.align-right{href: edit_project_path(project), class: "btn btn-default"}
          = fa_icon "pencil"
  %h2 Projects shared with me
  - @projects.each do |project|
    - project_class, access_indicator_class = case project.level
    - when 'r'
      -["project-readable", "project-access-indicator-readable"]
    - when 'w'
      -["project-writeable", "project-access-indicator-writeable"]
    - when 'm'
      -["project-manageable", "project-access-indicator-manageable"]
    .well.well-sm
      .project{class: project_class, id: "id#{project.id}"}
        %a.project-name{href: project_path(project) }= project.name
        .project-access-indicator.align-right{class: access_indicator_class}
        - if project.level.in? %w[w m]
          - is_current = project == current_user.current_project
          -cl = is_current ? "is-current btn btn-success disabled" : "is-not-current btn btn-default"
          -text = is_current ? "Current" : "Make current"
          -icon = is_current ? "check-square-o" : "square-o"
          =link_to project_set_as_current_path(project), class: "project-is-current-indicator #{cl} align-right" do 
            = fa_icon icon
            = text
        - if current_user.can_manage(project)
          %a.project-edit-link{href: edit_project_path(project), class: "btn btn-default"}
            = fa_icon "pencil"



//        %a.project-name{href: project_path(project)}= project.name
//        - if current_user.can_manage(project)
//          %a.project-edit-link{href: edit_project_path(project), class: "btn btn-default"}
//            = fa_icon "pencil"

app/views/projects/new.html.haml
.panel 
  %h2 New project
  -@action = :new
  = render "form"

app/views/projects/sharesettings.html.haml
.hidden.projects#sharesettings
.alert.alert-danger.modal#change-permission-error
  Couldn't change permission

.panel
  .panel-body
    %h3 Share settings

    =form_tag({controller: "projects", action: "share_with_user", id: @project.id}, method: "post", class: "form-horizontal", id: "share-user-add-user") do 
      .form-group
        =label_tag :username, nil, class: "control-label col-sm-2"
        .col-sm-6
          =text_field_tag :username, nil, class: "form-control"
        .col-sm-2 
          =submit_tag "Add user", class: "btn btn-default", data: {disable_with: false}

    #share-user-list
      .share-user.row
        .col-md-8
          .share-user-username=@project.owner.username
        .col-md-4
          .share-permission Owner
      - @project.users_with_permissions.each do |u|
        .share-user.row
          .hidden#username=u.username
          .col-sm-8
            .share-user-username=u.username
          .col-sm-4
            .hasJs#hasJs
              %select.share-permission{data: {username: u.username, level: u.level}, name: "level"}
                %option{value: 'r', selected: u.level == 'r'} Can read
                %option{value: 'w', selected: u.level == 'w'} Can write
                %option{value: 'm', selected: u.level == 'm'} Can manage
              =link_to "Kick", project_kick_user_path(@project), method: :post, class: "project-kick-user"
            %noscript
              :css
                .hasJs {display: none;}
              =form_tag project_set_user_permission_path(@project) do |f|
                =hidden_field_tag :username, u.username
                %select.share-permission{data: {username: u.username, level: u.level}, name: "level"}
                  %option{value: 'r', selected: u.level == 'r'} Can read
                  %option{value: 'w', selected: u.level == 'w'} Can write
                  %option{value: 'm', selected: u.level == 'm'} Can manage
                %button Save
              =link_to "Kick", project_kick_user_path(@project), method: :post , class: "project-kick-user"




    #examples-wrapper.hidden
      .share-user.row#example-share-user-row
        .hidden#username
        .col-md-8
          .share-user-username=@project.owner.username
        .col-md-4
          .hasJs#hasJs
            %select.share-permission{data: {username: '', level: 'r'}, name: "level"}
              %option{value: 'r'} Can read
              %option{value: 'w'} Can write
              %option{value: 'm'} Can manage
            =link_to "Kick", project_kick_user_path(@project), method: :post , class: "project-kick-user"

    .hidden
      #project_id=@project.id

app/views/projects/show.html.haml
.hidden.projects#show
%p#notice= notice

.panel
  .wrapper{style: "display: block; overflow: hidden;"}
    %h3.project-name.col-sm-6=@project.name
    .col-sm-6
      -if @can_leave
        =link_to "Leave project", leave_project_path(@project), method: :post, data: {confirm: "Are you sure?"}, class: "btn btn-warning"
      -if @can_manage
        %a.project-share-link{href: project_sharesettings_path(@project), class: "btn btn-default align-right", name: "Share settings"} Share settings
        %a.btn.btn-default{href: edit_project_path(@project)} Edit
      - if current_user.can_write(@project)
        - is_current = @project == current_user.current_project
        -cl = is_current ? "is-current btn btn-success disabled" : "is-not-current btn btn-default"
        -text = is_current ? "Current" : "Make current"
        -icon = is_current ? "check-square-o" : "square-o"
        =link_to project_set_as_current_path(@project), class: "project-is-current-indicator #{cl} align-right" do 
          = fa_icon icon
          = text



     
    .col-sm-12
      %p.project-owner
        %b Owner: 
        = link_to "@#{@project.owner.username}", microposts_path(filter: "user:#{@project.owner.username}")
    .col-sm-12
      %p
        %b Git: 
        %a.project-git-url{href: @project.git_url}=@project.git_url
    .col-sm-12
      %a.project-microposts-link{href: project_microposts_path(@project), class: "btn btn-default"} Microposts
      %a.project-publications-link{href: project_publications_path(@project), class: "btn btn-default"} Publications
    .col-sm-12
      %h4 Description:
      %p.project-description= @project.description



    