config/routes.rb
Rails.application.routes.draw do
    devise_scope :user do
        authenticated :user do 
            root to: 'home#dashboard', as: :authenticated_root
        end

        unauthenticated do
            root to: 'devise/sessions#new', as: :unauthenticated_root
        end
    end

    root to: 'home#index'
  devise_for :users

  resources :microposts, except: :new, constraints: {id: /[0-9]+/}
  post '/microposts/:id/add_to_current_report', to: 'microposts#add_to_current_report', as: 'add_mp_to_current_report'
  post '/microposts/:id/remove_from_current_report', to: 'microposts#remove_from_current_report', as: 'remove_mp_from_current_report'
  resources :publications
  get '/publications/:id/pdf', to: 'publications#pdf', as: 'publication_pdf'
  get '/microposts/:id/tex', to: 'microposts#tex', as: 'micropost_tex'
  get '/publications/:id/info', to: 'publications#info', as: 'publication_info'
  post '/misc/getPublicationIds', to: 'publications#getIds'
  resources :projects do
  end
  post '/projects/:id/leave', to: 'projects#leave', as: "leave_project"
  get '/projects/:id/microposts', to: 'projects#microposts', as: "project_microposts"
  get '/projects/:id/publications', to: 'projects#publications', as: "project_publications"
  get '/projects/:id/sharesettings', to: 'projects#sharesettings', as: "project_sharesettings"
  post '/projects/:id/share_with_user', to: 'projects#share_with_user', as: "project_share_with_user"
  post '/projects/:id/set_user_permission', to: 'projects#set_user_permission', as: "project_set_user_permission"
  post '/projects/:id/kick_user', to: 'projects#kick_user', as: "project_kick_user"
  post '/projects/:id/set_as_current', to: 'projects#set_as_current', as: "project_set_as_current"
  get '/projects/:project_id/publication/:id', to: 'publications#show', as: "project_publication"
  resources :reports do 
  end
  post '/reports/:id/leave', to: 'reports#leave', as: "leave_report"
  get '/reports/:id/microposts', to: 'reports#microposts', as: "report_microposts"
  get '/reports/:id/publications', to: 'reports#publications', as: "report_publications"
  get '/reports/:id/sharesettings', to: 'reports#sharesettings', as: "report_sharesettings"
  post '/reports/:id/share_with_user', to: 'reports#share_with_user', as: "report_share_with_user"
  post '/reports/:id/set_user_permission', to: 'reports#set_user_permission', as: "report_set_user_permission"
  post '/reports/:id/kick_user', to: 'reports#kick_user', as: "report_kick_user"
  post '/reports/:id/set_as_current', to: 'reports#set_as_current', as: "report_set_as_current"
  get '/reports/:report_id/publication/:id', to: 'publications#show', as: "report_publication"

  get '/users/:username/stats', to: 'user#stats', as: "user_stats"
  get '/users/:username', to: 'user#show', as: "user"
  get '/users/:username/microposts', to: 'user#microposts', as: "user_microposts"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mathjax 'mathjax'

  get '/settings', to: 'user#settings'
  put '/settings/update_password', to: 'user#update_password'

end

app/models/micropost.rb
require 'microposts_filter'
class Micropost < ApplicationRecord
  attr_accessor :content_archive
  before_destroy :clean_files, prepend: true
  belongs_to :project
  belongs_to :user

  has_and_belongs_to_many :reports
  validates_presence_of :user
  validates_presence_of :tex
  validates_presence_of :html
  validates_presence_of :content_path
  validates_presence_of :project

  scope :written_by, -> (user_id) {where user_id: user}
  scope :in_project, -> (project_id) {where project_id: project_id}

  def save_file(file)
    relative_filepath = Time.now.strftime('%Y-%m-%d_%H-%M-%S_%L')
    path = Rails.root.join("public","system","micropost_contents", relative_filepath)
    FileUtils.mkdir_p(path)

    system("tar -zxvf #{file.path} -C #{path} --strip-components=1 > /dev/null")
    self.content_path = relative_filepath


    return $?.exitstatus <= 0
  end

  def clean_files
    system "rm -R #{full_content_path(self.content_path)}"
  end

  def good_html
    h = vary_references(self.html)
    h.gsub!(":project_id", project.id.to_s)
    h.gsub!("data-href-dummy","href")
    h
  end


  def full_content_path(path = nil)
    if (path.nil?)
      Rails.root.join("public","system","micropost_contents",self.content_path)
    else
      Rails.root.join("public","system","micropost_contents",path)
    end
  end

  def self.filter(query, current_user)
    f = MicropostsFilter.new
    f.current_user = current_user
    f.query = query
    p f
    return f.microposts
  end



  def add_to_report(report)
      report.microposts << self
  end


  def remove_from_report(report)
      reports.delete report
  end

  private

  def vary_references(html)
    if (html)
      modhtml = html.gsub(/a class="ref" href="#([^"]+)" ref="([^"]+)"/, "a class=\"ref\" href=\"#\\1_#{hash}\" ref=\"\\1_#{hash}\"")
      modhtml = modhtml.gsub(/<span class="label" id="([^"]+)">/, "<span class=\"label\" id=\"\\1_#{hash}\">")
      return modhtml
    else 
      return ""
    end

  end


  def hash
    Digest::MD5.hexdigest(self.created_at.to_s)[0..6]
  end

end

app/controllers/microposts_controller.rb
require Rails.root.join("lib/parser/parser.rb")
class MicropostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_micropost, only: [:show, :edit, :update, :destroy, :tex, :add_to_current_report, :remove_from_current_report]
    skip_before_action :verify_authenticity_token

    # GET /microposts
    # GET /microposts.json
    def index
      @query = params[:filter]
      if params[:filter]
        @microposts = Micropost.filter params[:filter], current_user
      else
        @microposts = Micropost.filter "", current_user
      end
    end

    # GET /microposts/1
    # GET /microposts/1.json
    def show
      p current_user.can_read @micropost.project
      (render_404 and return) unless current_user.can_read @micropost.project
    end


    # GET /microposts/1/edit
    def edit
        (render_404 and return) unless current_user == @micropost.user
    end

    # POST /microposts
    # POST /microposts.json
    def create
        @micropost = current_user.current_project.microposts.new(micropost_params)
        @micropost.user = current_user
        p @micropost
        file_saved = @micropost.save_file(micropost_file)
        
        tex = micropost_params[:tex]
        th = TexConverter::TexHandler.new
        th.relative_path = "/system/micropost_contents/#{@micropost.content_path}"
        th.user_id = current_user.id
        parseResult = th.texToHtml tex 

        s = parseResult[:status]
        if s.empty?
            html = parseResult[:tree]
            @micropost.html = html
        end


        respond_to do |format|
            if file_saved and @micropost.save
                format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
                format.json { render :show, status: :created, location: @micropost }
            else
                @micropost.clean_files
                format.html { render :new }
                format.json { render json: @micropost.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /microposts/1
    # PATCH/PUT /microposts/1.json
    def update
        (render_404 and return) unless @micropost.user == current_user
        respond_to do |format|
            if @micropost.update(micropost_params)
                format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
                format.json { render :show, status: :ok, location: @micropost }
            else
                format.html { render :edit }
                format.json { render json: @micropost.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /microposts/1
    # DELETE /microposts/1.json
    def destroy
        @micropost.destroy
        respond_to do |format|
            format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    def tex
        render plain: @micropost.tex, layout: false
    end

    def add_to_current_report
        (render_404 and return) unless current_user.can_read @micropost.project
        @micropost.add_to_report current_user.current_report

        render json: {status: "success"}
    end
    def remove_from_current_report
        (render_404 and return) unless current_user.can_read @micropost.project

        @micropost.remove_from_report current_user.current_report

        render json: {status: "success"}
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
        @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
        params.fetch(:micropost, {}).permit(:commit, :tex, :project_id)
    end

    def micropost_file
        params.fetch(:micropost, {}).permit(:content_archive)[:content_archive]
    end



end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.haml
= form_with(model: micropost, local: true) do |form|
  - if micropost.errors.any?
    #error_explanation
      %h2
        = pluralize(micropost.errors.count, "error")
        prohibited this micropost from being saved:
      %ul
        - micropost.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/microposts/_micropost_block.html.haml
- timestamp = mp.created_at.to_i.to_s
.panel.panel-default.micropost.micropost_block{:id => timestamp}
  .panel-heading
    %h6= mp.created_at.strftime('%d.%m.%y, %H:%M:%S')
    %h6
      = link_to "TeX", micropost_tex_path(mp.id), target: :_blank
      ,
      = link_to "Edit", edit_micropost_path(mp.id)
    %h6
      - if mp.in? current_user.current_report.microposts
        = link_to "Remove from current report", remove_mp_from_current_report_path(mp), method: :post, target: :_blank
      - else
        = link_to "Add to current report", add_mp_to_current_report_path(mp), method: :post, target: :_blank
    %h6
      Project:
      =link_to mp.project.name, project_path(mp.project)
    %h6
      Author:
      = link_to "@#{mp.user.username}", user_path(username: mp.user.username)
  .panel-body
    != mp.good_html
    - if mp.user_id == current_user.id
      = button_to "Delete", micropost_path(mp.id), method: :delete, class: "btn btn-warning"

app/views/microposts/edit.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Edit micropost #{@micropost.id}
  .panel-body
    = form_for @micropost do |f|
      .form-group
        = f.label :project
        = f.collection_select(:project_id, current_user.all_projects, :id, :name, class: "form-control")
      .actions
        = f.submit 'Save', class: "btn btn-primary"

app/views/microposts/index.html.haml
.hidden.microposts#index
.panel
  =form_tag microposts_path, class: "form form-horizontal", style: "display: block; overflow: hidden", method: :get do
    =label_tag :filter, nil, class: "col-sm-1 control-label"
    .col-sm-8
      =text_field_tag :filter, nil, class: "form-control", value: @query
    =submit_tag 'Apply', class: "btn btn-default col-sm-2"
- if @microposts.empty?
  %p No microposts found
- else 
  .infinite-table{style: "display: block; overflow: hidden"}
    - @microposts.each do |mp|
      = render partial: 'micropost_block', object: mp, as: 'mp'

app/views/microposts/new.html.haml
%h1 New Micropost
= render 'form', micropost: @micropost
= link_to 'Back', microposts_path

app/views/microposts/show.html.haml
.hidden.microposts#index
= render partial: 'micropost_block', object: @micropost, as: 'mp'