config/routes.rb
Rails.application.routes.draw do
    devise_scope :user do
        authenticated :user do 
            root to: 'home#dashboard', as: :authenticated_root
        end

        unauthenticated do
            root to: 'devise/sessions#new', as: :unauthenticated_root
        end
    end

    root to: 'home#index'
  devise_for :users

  resources :microposts, except: :new, constraints: {id: /[0-9]+/}
  post '/microposts/:id/add_to_current_report', to: 'microposts#add_to_current_report', as: 'add_mp_to_current_report'
  post '/microposts/:id/remove_from_current_report', to: 'microposts#remove_from_current_report', as: 'remove_mp_from_current_report'
  resources :publications
  get '/publications/:id/pdf', to: 'publications#pdf', as: 'publication_pdf'
  get '/microposts/:id/tex', to: 'microposts#tex', as: 'micropost_tex'
  get '/publications/:id/info', to: 'publications#info', as: 'publication_info'
  post '/misc/getPublicationIds', to: 'publications#getIds'
  resources :projects do
  end
  post '/projects/:id/leave', to: 'projects#leave', as: "leave_project"
  get '/projects/:id/microposts', to: 'projects#microposts', as: "project_microposts"
  get '/projects/:id/publications', to: 'projects#publications', as: "project_publications"
  get '/projects/:id/sharesettings', to: 'projects#sharesettings', as: "project_sharesettings"
  post '/projects/:id/share_with_user', to: 'projects#share_with_user', as: "project_share_with_user"
  post '/projects/:id/set_user_permission', to: 'projects#set_user_permission', as: "project_set_user_permission"
  post '/projects/:id/kick_user', to: 'projects#kick_user', as: "project_kick_user"
  post '/projects/:id/set_as_current', to: 'projects#set_as_current', as: "project_set_as_current"
  get '/projects/:project_id/publication/:id', to: 'publications#show', as: "project_publication"
  resources :reports do 
  end
  post '/reports/:id/leave', to: 'reports#leave', as: "leave_report"
  get '/reports/:id/microposts', to: 'reports#microposts', as: "report_microposts"
  get '/reports/:id/publications', to: 'reports#publications', as: "report_publications"
  get '/reports/:id/sharesettings', to: 'reports#sharesettings', as: "report_sharesettings"
  post '/reports/:id/share_with_user', to: 'reports#share_with_user', as: "report_share_with_user"
  post '/reports/:id/set_user_permission', to: 'reports#set_user_permission', as: "report_set_user_permission"
  post '/reports/:id/kick_user', to: 'reports#kick_user', as: "report_kick_user"
  post '/reports/:id/set_as_current', to: 'reports#set_as_current', as: "report_set_as_current"
  get '/reports/:report_id/publication/:id', to: 'publications#show', as: "report_publication"

  get '/users/:username/stats', to: 'user#stats', as: "user_stats"
  get '/users/:username', to: 'user#show', as: "user"
  get '/users/:username/microposts', to: 'user#microposts', as: "user_microposts"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mathjax 'mathjax'

  get '/settings', to: 'user#settings'
  put '/settings/update_password', to: 'user#update_password'

end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :owner, class_name: "User"
    has_and_belongs_to_many :microposts

    has_many :user_reports

    has_many :users, through: :user_reports, source: :user

    has_many :user_reports_readable, -> {where level: 'r'}, class_name: "UserReport"
    has_many :readers, class_name: "User", through: :user_reports_readable, source: :user

    has_many :user_reports_writeable, -> {where level: 'w'}, class_name: "UserReport"
    has_many :writers,  class_name: "User", through: :user_reports_writeable, source: :user

    has_many :user_reports_manageable, -> {where level: 'm'}, class_name: "UserReport"
    has_many :managers,  class_name: "User", through: :user_reports_manageable, source: :user

    before_save :create_share_link
    before_destroy :destroy_shares
    validates_presence_of :owner
    validates_presence_of :name
    validates_uniqueness_of :share_link


    def compile
        tar_name = SecureRandom.hex
        Dir.mktmpdir do |dir|
            microposts.each do |mp|
                mp.copy_contents_to dir

                # make archive
                #
            end
            `tar c dir | gzip > /tmp/#{tar_name}.tar.gz` 
        end
    end


    def add_reader(user)
        begin 
            self.users.delete user
            self.readers << user
        end  unless user == owner
    end

    def add_readers(users)
        begin 
            self.users.delete users
            self.readers << users.select{|user| user != owner}
        end 
    end

    def add_writer(user)
        begin 
            self.users.delete user
            self.writers << user 
        end unless user == owner
    end
    def add_writers(users)
        begin 
            self.users.delete users
            self.writers << users.select{|user| user != owner}
        end
    end

    def add_manager(user)
        begin 
            self.users.delete user
            self.managers << user 
        end unless user == owner
    end
    def add_managers(users)
        begin 
            self.users.delete users
            self.managers << users.select{|user| user != owner}
        end
    end

    def kick user
        self.users.delete user
    end

    def pass_ownership_to user
        prev_owner = self.owner
        self.owner = user
        save
        add_manager prev_owner
    end

    def change_permission user, permission
        u_p = user_reports.find_by(user_id: user.id)
        if u_p 
            u_p.set_permission permission
            u_p.save
        else
            case permission
            when :write
                add_writer user
            when :read 
                add_reader user
            when :manage
                add_manager user
            end
        end
    end

    def user_permission user
        u_p = user_reports.find_by(user_id: user.id) and u_p.permission
    end

    def create_share_link
        self.share_link = SecureRandom.urlsafe_base64(32)
    end

    def share_by_link
        self.is_shared_with_link = true
    end

    def stop_sharing_by_link
        self.is_shared_with_link = false
    end


    def all_users
        users.to_a << owner
    end


    def users_with_permissions
      self.users.select('*, users.id as id, user_reports.level as level').map
    end

    private
    def destroy_shares
        self.user_reports.delete_all
    end


end

app/controllers/reports_controller.rb
require Rails.root.join('app/models/user_report.rb')
class ReportsController < ApplicationController 
  before_action :authenticate_user!
  before_action :set_report, except: %i[index new create share_with_user]
  before_action :set_permissions, except: %i[index new create share_with_user]

  # GET /reports
  # GET /reports.json
  def index
    @own_reports = current_user.own_reports
    @reports = current_user.reports_with_permissions
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    (render_404 and return) unless @can_read
  end

  # GET /reports/new
  def new
    @report = Report.new
    @report.owner_id = current_user.id
  end

  # GET /reports/1/edit
  def edit;
    (render_404 and return) unless @can_manage
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params.permit(%i[owner_id name description git_url]) )

    respond_to do |format|
      if @report.save
        format.html do
          redirect_to @report,
            notice: 'Report was successfully created.'
        end
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    (render_404 and return) unless @can_manage
    respond_to do |format|
      if @report.update(report_params.permit(%i[name git_url description]) )
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def leave
    unless @can_leave
      redirect_to report_path(@report), flash: { error: "You can't leave your own report. You may delete it or pass ownership to somebody else." }
    end

    current_user.leave_report(@report)
    redirect_to reports_path, notice: "You've left report #{@report.name}"
  end

  def sharesettings
    unless @can_manage
      redirect_to report_path(@report), flash: { error: "You don't have rights to manage this report" }
    end
  end

  def share_with_user
    prms = params.permit([:username, :id, :async])
    @report = Report.find_by(id: prms[:id])
    set_permissions
    (render_404 and return) unless @can_manage

    username = prms[:username]
    @user = User.find_by(username: username)
    errors = []
    status = :success
    user = nil

    if @report.nil?
      errors << "No report found with id #{prms[:id]}"
      status = :fail
    elsif @user.nil?
      errors << "No user found with username #{username}"
      status = :fail
    elsif @user.in? @report.users
      errors << "User #{username} already has permissions in this report"
      status = :fail
    elsif @user == @report.owner
      errors << "User #{username} is owner of this report"
      status = :fail
    else
      if @report.add_reader @user 
        status = :success
        user = @user
      else
        status = :fail
        errors << "Unknown error"
      end
    end

    if prms[:async]
      render json: {status: status, errors: errors, user: user.to_json}
    else 
      redirect_to report_sharesettings_path(@report)
    end
  end
  
  def set_user_permission 
    (render_404 and return) unless @can_manage
    prms = params.permit([:username, :level, :async, :id])

    user = User.find_by(username: prms[:username])
    level = prms[:level]
    async = prms[:async]

    errors = []
    status = :success
    permission = UserReport::ClassMethods.level_to_permission level

    if user.nil?
      status = :fail
      errors << "No user found with id #{prms[:username]}"
    elsif !(user.in? @report.users)
      status = :fail
      errors << "User #{user.username} isn't participating in this report"
    else
      if @report.change_permission user, permission
        status = :success
      else
        status = :fail
        errors << "Unknown error"
      end
    end

    if async
      render json: {status: status, errors: errors, level: level}
    else
      #redirect_to report_sharesettings_path(@report)
      redirect_to report_sharesettings_path(@report)
    end

  end

  def kick_user
    (render_404 and return) unless @can_manage
    prms = params.permit([:username, :async])
    user = User.find_by username: prms[:username]
    errors = []
    status = :success

    if user.nil?
      status = :fail
      errors << "No user found with id #{prms[:username]}"
    elsif user == @report.owner
      status = :fail
      errors << "Can't kick owner"
    elsif !(user.in? @report.users)
      status = :fail
      errors << "User with id #{prms[:username]} isn't participant of this report"
    else
      if @report.kick user
        status = :success
      else
        status = :fail
        errors << "Unknown error"
      end
    end

    if prms[:async]
      render json: {status: status, errors: errors}
    else
      redirect_to report_sharesettings_path(@report)
    end


  end

  def set_as_current
    (render_404 and return) unless @can_write

    current_user.current_report = @report

    render json: {status: "success"}
  end

  def microposts
    redirect_to microposts_path(filter: "report:##{@report.id}")
  end

  def publications
    redirect_to publications_path(filter: "report:##{@report.id}")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find_by(id: params[:id])
    render_404 if @report.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.fetch(:report, {})
  end

  def set_permissions
    @is_owner = @report.owner == current_user
    @can_leave = !@is_owner
    if @is_owner
      @can_manage = true
      @can_write = true
      @can_read = true
    else
      perm = @report.user_permission(current_user)
      unless perm.nil?
        @can_read = perm.in? %i[read write manage]
        @can_write = perm.in? %i[write manage]
        @can_manage = perm.in? [:manage]
      end
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.haml
= form_for @report, html: { class: " form-horizontal" } do |f|
  - if @report.errors.any?
    #error_explanation
      %h2= "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      %ul
        - @report.errors.full_messages.each do |msg|
          %li= msg
  =f.hidden_field :owner_id
  .form-group
    =f.label :name, class: "control-label col-sm-2"
    .col-sm-10
      =f.text_field :name, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      -if @action == :edit
        = f.submit 'Save', class: 'btn btn-default'
      -else
        = f.submit 'Create', class: 'btn btn-default'

app/views/reports/edit.html.haml
.panel
  %h2 Editing report

  -@action = :edit
  =render 'form'

app/views/reports/index.html.haml
.hidden.reports#index
.panel 
  .row
    .col-md-8
      %h2 My reports
    .col-md-4
      %a.btn.btn-primary.align-right{href: new_report_path}
        Create report
  - @own_reports.each do |report|
    .well.well-sm
      .report.own-report{id: "id#{report.id}"}
        %a.report-name{href: report_path(report)}= report.name
        - is_current = report == current_user.current_report
        -cl = is_current ? "is-current btn btn-success disabled" : "is-not-current btn btn-default"
        -text = is_current ? "Current" : "Make current"
        -icon = is_current ? "check-square-o" : "square-o"
        =link_to report_set_as_current_path(report), class: "report-is-current-indicator #{cl} align-right" do 
          = fa_icon icon
          = text
          

        .report-privacy-indicator.align-right{class: report.is_shared_with_link ? "report-shared-with-link" : ""}
        %a.report-edit-link.align-right{href: edit_report_path(report), class: "btn btn-default"}
          = fa_icon "pencil"
  %h2 Reports shared with me
  - @reports.each do |report|
    - report_class, access_indicator_class = case report.level
    - when 'r'
      -["report-readable", "report-access-indicator-readable"]
    - when 'w'
      -["report-writeable", "report-access-indicator-writeable"]
    - when 'm'
      -["report-manageable", "report-access-indicator-manageable"]
    .well.well-sm
      .report{class: report_class, id: "id#{report.id}"}
        %a.report-name{href: report_path(report) }= report.name
        .report-access-indicator.align-right{class: access_indicator_class}
        - if report.level.in? %w[w m]
          - is_current = report == current_user.current_report
          -cl = is_current ? "is-current btn btn-success disabled" : "is-not-current btn btn-default"
          -text = is_current ? "Current" : "Make current"
          -icon = is_current ? "check-square-o" : "square-o"
          =link_to report_set_as_current_path(report), class: "report-is-current-indicator #{cl} align-right" do 
            = fa_icon icon
            = text
        - if current_user.can_manage(report)
          %a.report-edit-link{href: edit_report_path(report), class: "btn btn-default"}
            = fa_icon "pencil"



//        %a.report-name{href: report_path(report)}= report.name
//        - if current_user.can_manage(report)
//          %a.report-edit-link{href: edit_report_path(report), class: "btn btn-default"}
//            = fa_icon "pencil"

app/views/reports/new.html.haml
.panel 
  %h2 New report
  -@action = :new
  = render "form"

app/views/reports/sharesettings.html.haml
.hidden.reports#sharesettings
.alert.alert-danger.modal#change-permission-error
  Couldn't change permission

.panel
  .panel-body
    %h3 Share settings

    =form_tag({controller: "reports", action: "share_with_user", id: @report.id}, method: "post", class: "form-horizontal", id: "share-user-add-user") do 
      .form-group
        =label_tag :username, nil, class: "control-label col-sm-2"
        .col-sm-6
          =text_field_tag :username, nil, class: "form-control"
        .col-sm-2 
          =submit_tag "Add user", class: "btn btn-default", data: {disable_with: false}

    #share-user-list
      .share-user.row
        .col-md-8
          .share-user-username=@report.owner.username
        .col-md-4
          .share-permission Owner
      - @report.users_with_permissions.each do |u|
        .share-user.row
          .hidden#username=u.username
          .col-sm-8
            .share-user-username=u.username
          .col-sm-4
            .hasJs#hasJs
              %select.share-permission{data: {username: u.username, level: u.level}, name: "level"}
                %option{value: 'r', selected: u.level == 'r'} Can read
                %option{value: 'w', selected: u.level == 'w'} Can write
                %option{value: 'm', selected: u.level == 'm'} Can manage
              =link_to "Kick", report_kick_user_path(@report), method: :post, class: "report-kick-user"
            %noscript
              :css
                .hasJs {display: none;}
              =form_tag report_set_user_permission_path(@report) do |f|
                =hidden_field_tag :username, u.username
                %select.share-permission{data: {username: u.username, level: u.level}, name: "level"}
                  %option{value: 'r', selected: u.level == 'r'} Can read
                  %option{value: 'w', selected: u.level == 'w'} Can write
                  %option{value: 'm', selected: u.level == 'm'} Can manage
                %button Save
              =link_to "Kick", report_kick_user_path(@report), method: :post , class: "report-kick-user"




    #examples-wrapper.hidden
      .share-user.row#example-share-user-row
        .hidden#username
        .col-md-8
          .share-user-username=@report.owner.username
        .col-md-4
          .hasJs#hasJs
            %select.share-permission{data: {username: '', level: 'r'}, name: "level"}
              %option{value: 'r'} Can read
              %option{value: 'w'} Can write
              %option{value: 'm'} Can manage
            =link_to "Kick", report_kick_user_path(@report), method: :post , class: "report-kick-user"

    .hidden
      #report_id=@report.id

app/views/reports/show.html.haml
.hidden.reports#show
%p#notice= notice

.panel
  .wrapper{style: "display: block; overflow: hidden;"}
    %h3.report-name.col-sm-6=@report.name
    .col-sm-6
      -if @can_leave
        =link_to "Leave report", leave_report_path(@report), method: :post, data: {confirm: "Are you sure?"}, class: "btn btn-warning"
      -if @can_manage
        %a.report-share-link{href: report_sharesettings_path(@report), class: "btn btn-default align-right", name: "Share settings"} Share settings
        %a.btn.btn-default{href: edit_report_path(@report)} Edit
      - if current_user.can_write(@report)
        - is_current = @report == current_user.current_report
        -cl = is_current ? "is-current btn btn-success disabled" : "is-not-current btn btn-default"
        -text = is_current ? "Current" : "Make current"
        -icon = is_current ? "check-square-o" : "square-o"
        =link_to report_set_as_current_path(@report), class: "report-is-current-indicator #{cl} align-right" do 
          = fa_icon icon
          = text



     
    .col-sm-12
      %p.report-owner
        %b Owner: 
        = link_to "@#{@report.owner.username}", microposts_path(filter: "user:#{@report.owner.username}")
    .col-sm-12
    .col-sm-12
      %a.report-microposts-link{href: report_microposts_path(@report), class: "btn btn-default"} Microposts
      %a.report-publications-link{href: report_publications_path(@report), class: "btn btn-default"} Publications



    